name: build

on:
  workflow_call:
    inputs:
      branch:
        description: branch to build
        required: false
        default: public
        type: string

  workflow_dispatch:
    inputs:
      branch:
        description: branch to build
        required: false
        type: choice
        default: public
        options:
          - public
          - contact
          - profiling
          - creatordlc

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: checkout repository
        uses: actions/checkout@v6.0.1

      - name: get build_id from build.txt
        id: get_build
        run: |
          BUILD=$(cat build.txt | tr -d ' \n')
          echo "build_id=$BUILD" >> $GITHUB_OUTPUT

      - name: check if release already exists
        id: check_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ steps.get_build.outputs.build_id }}
        run: |
          if gh release view "$TAG" >/dev/null 2>&1; then
            echo "Release $TAG already exists. Skipping build."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: build image
        run: |
          IMAGE=${{ github.repository }}
          ls -la
          docker build . \
            --tag $IMAGE:local \
            --build-arg STEAM_USER=${{ secrets.STEAM_USER }} \
            --build-arg STEAM_PASS=${{ secrets.STEAM_PASS }} \
            --build-arg BRANCH=${{ inputs.branch }}

      - name: extract game version
        if: steps.check_release.outputs.exists == 'false'
        id: get_version
        run: |
          IMAGE="${{ github.repository }}:local"
          # VERSION=$(docker run --rm --entrypoint sh $IMAGE -c "strings /home/steam/arma3/arma3server | grep -oP 'Arma 3 Console version \K[0-9]+\.[0-9]+\.[0-9]+'")
          # VERSION=$(docker run --rm --entrypoint sh $IMAGE -c "/home/steam/arma3/arma3server --version 2>&1 | sed -n 's/.*ver\. \([0-9.]*\).*/\1/p'")
          VERSION=$(docker run --rm $IMAGE --version 2>&1 | sed -n 's/.*ver\. \([0-9.]*\).*/\1/p')
          echo "version=v$VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: log in to container registry [github]
        if: steps.check_release.outputs.exists == 'false'
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: log in to container registry [docker]
        if: steps.check_release.outputs.exists == 'false'
        uses: docker/login-action@v3.6.0
        with:
          registry: docker.io
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: tag image
        if: steps.check_release.outputs.exists == 'false'
        run: |
          docker tag ${{ github.repository }}:local ghcr.io/${{ github.repository }}:v${{ steps.get_version.outputs.version }}
          docker tag ${{ github.repository }}:local ghcr.io/${{ github.repository }}:${{ steps.get_version.outputs.version }}
          docker tag ${{ github.repository }}:local ghcr.io/${{ github.repository }}:depot-${{ steps.get_build.outputs.build_id }}
          docker tag ${{ github.repository }}:local ghcr.io/${{ github.repository }}:latest
          docker tag ${{ github.repository }}:local docker.io/${{ github.repository }}:v${{ steps.get_version.outputs.version }}
          docker tag ${{ github.repository }}:local docker.io/${{ github.repository }}:${{ steps.get_version.outputs.version }}
          docker tag ${{ github.repository }}:local docker.io/${{ github.repository }}:depot-${{ steps.get_build.outputs.build_id }}
          docker tag ${{ github.repository }}:local docker.io/${{ github.repository }}:latest

      - name: push image
        if: steps.check_release.outputs.exists == 'false'
        run: |
          docker push ghcr.io/${{ github.repository }}:v${{ steps.get_version.outputs.version }}
          docker push ghcr.io/${{ github.repository }}:${{ steps.get_version.outputs.version }}
          docker push ghcr.io/${{ github.repository }}:depot-${{ steps.get_build.outputs.build_id }}
          docker push ghcr.io/${{ github.repository }}:latest
          docker push docker.io/${{ github.repository }}:v${{ steps.get_version.outputs.version }}
          docker push docker.io/${{ github.repository }}:${{ steps.get_version.outputs.version }}
          docker push docker.io/${{ github.repository }}:depot-${{ steps.get_build.outputs.build_id }}
          docker push docker.io/${{ github.repository }}:latest

      - name: create github release
        if: steps.check_release.outputs.exists == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD: ${{ steps.get_build.outputs.build_id }}
          VERSION: ${{ steps.get_version.outputs.version }}
        run: |
          gh release create "$BUILD" \
            --title "v$VERSION" \
            --notes "Build ID: $BUILD | Internal Game Version: $VERSION"
