name: build

on:
  workflow_call:
    inputs:
      branch:
        description: branch to build
        required: false
        default: public
        type: string

  workflow_dispatch:
    inputs:
      branch:
        description: branch to build
        required: false
        type: choice
        default: public
        options:
          - public
          - contact
          - profiling
          - creatordlc

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: checkout repository
        uses: actions/checkout@v6.0.1

      - name: get build_id from build.json
        id: get_build
        run: |
          BRANCH="${{ inputs.branch }}"
          BUILD=$(jq -r ".[] | select(.branch == \"$BRANCH\") | .build_id" build.json)

          if [ -z "$BUILD" ] || [ "$BUILD" = "null" ]; then
            echo "No build_id found for branch $BRANCH"
            exit 1
          fi
          echo "build_id=$BUILD" >> "$GITHUB_OUTPUT"

      - name: check if docker image exists
        id: check_exists
        run: |
          IMAGE="ghcr.io/${{ github.repository }}:${{ inputs.branch }}-${{ steps.get_build.outputs.build_id }}"
          
          if docker manifest inspect "$IMAGE" > /dev/null 2>&1; then
            echo "Image $IMAGE already exists. Skipping build."
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: build image
        run: |
          IMAGE=${{ github.repository }}
          ls -la
          docker build . \
            --tag $IMAGE:local \
            --build-arg STEAM_USER=${{ secrets.STEAM_USER }} \
            --build-arg STEAM_PASS=${{ secrets.STEAM_PASS }} \
            --build-arg BRANCH=${{ inputs.branch }}

      - name: extract game version
        if: steps.check_exists.outputs.exists == 'false'
        id: get_version
        run: |
          IMAGE="${{ github.repository }}:local"
          # VERSION=$(docker run --rm --entrypoint sh $IMAGE -c "strings /home/steam/arma3/arma3server | grep -oP 'Arma 3 Console version \K[0-9]+\.[0-9]+\.[0-9]+'")
          # VERSION=$(docker run --rm --entrypoint sh $IMAGE -c "/home/steam/arma3/arma3server --version 2>&1 | sed -n 's/.*ver\. \([0-9.]*\).*/\1/p'")
          VERSION=$(docker run --rm $IMAGE --version 2>&1 | sed -n 's/.*ver\. \([0-9.]*\).*/\1/p')
          echo "version=v$VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: log in to container registry [github]
        if: steps.check_exists.outputs.exists == 'false'
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: log in to container registry [docker]
        if: steps.check_exists.outputs.exists == 'false'
        uses: docker/login-action@v3.6.0
        with:
          registry: docker.io
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: tag image for public branch
        if: ${{ inputs.branch == 'public' && steps.check_exists.outputs.exists == 'false' }}
        run: |
          docker tag ${{ github.repository }}:local ghcr.io/${{ github.repository }}:latest
          docker tag ${{ github.repository }}:local docker.io/${{ github.repository }}:latest
          docker tag ${{ github.repository }}:local ghcr.io/${{ github.repository }}:${{ inputs.branch }}-${{ steps.get_build.outputs.build_id }}
          docker tag ${{ github.repository }}:local docker.io/${{ github.repository }}:${{ inputs.branch }}-${{ steps.get_build.outputs.build_id }}

      - name: tag image for non-public branch
        if: ${{ inputs.branch != 'public' && steps.check_exists.outputs.exists == 'false' }}
        run: |
          docker tag ${{ github.repository }}:local ghcr.io/${{ github.repository }}:${{ inputs.branch }}-${{ steps.get_build.outputs.build_id }}
          docker tag ${{ github.repository }}:local docker.io/${{ github.repository }}:${{ inputs.branch }}-${{ steps.get_build.outputs.build_id }}

      - name: push image for public branch
        if: ${{ inputs.branch == 'public' && steps.check_exists.outputs.exists == 'false' }}
        run: |
          docker push ${{ github.repository }}:local ghcr.io/${{ github.repository }}:latest
          docker push ${{ github.repository }}:local docker.io/${{ github.repository }}:latest
          docker push ${{ github.repository }}:local ghcr.io/${{ github.repository }}:${{ inputs.branch }}-${{ steps.get_build.outputs.build_id }}
          docker push ${{ github.repository }}:local docker.io/${{ github.repository }}:${{ inputs.branch }}-${{ steps.get_build.outputs.build_id }}

      - name: push image for non-public branch
        if: ${{ inputs.branch != 'public' && steps.check_exists.outputs.exists == 'false' }}
        run: |
          docker push ${{ github.repository }}:local ghcr.io/${{ github.repository }}:${{ inputs.branch }}-${{ steps.get_build.outputs.build_id }}
          docker push ${{ github.repository }}:local docker.io/${{ github.repository }}:${{ inputs.branch }}-${{ steps.get_build.outputs.build_id }}
