name: build

on:
  workflow_call:
    inputs:
      branch:
        description: branch to build
        required: false
        default: public
        type: string

  workflow_dispatch:
    inputs:
      branch:
        description: branch to build
        required: false
        type: choice
        default: public
        options:
          - public
          - contact
          - profiling
          - creatordlc

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      build_id: ${{ steps.get_build.outputs.build_id }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v6.0.1

      - name: get build_id from build.json
        id: get_build
        run: |
          BRANCH="${{ inputs.branch }}"
          BUILD=$(jq -r ".[] | select(.branch == \"$BRANCH\") | .build_id" build.json)

          if [ -z "$BUILD" ] || [ "$BUILD" = "null" ]; then
            echo "No build_id found for branch $BRANCH"
            exit 1
          fi
          echo "build_id=$BUILD" >> "$GITHUB_OUTPUT"

  check-image:
    runs-on: ubuntu-latest
    needs: prepare
    outputs:
      exists: ${{ steps.check_exists.outputs.exists }}
    steps:
      - name: check if docker image exists
        id: check_exists
        run: |
          IMAGE="ghcr.io/${{ github.repository }}:${{ inputs.branch }}-${{ needs.prepare.outputs.build_id }}"
          if docker manifest inspect "$IMAGE" > /dev/null 2>&1; then
            echo "Image exists"
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

  build:
    runs-on: ubuntu-latest
    needs: [prepare, check-image]
    if: needs.check-image.outputs.exists == 'false'
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v6.0.1

      - name: build Docker image
        run: |
          IMAGE=${{ github.repository }}
          docker build . \
            --tag $IMAGE:local \
            --build-arg STEAM_USER=${{ secrets.STEAM_USER }} \
            --build-arg STEAM_PASS=${{ secrets.STEAM_PASS }} \
            --build-arg BRANCH=${{ inputs.branch }}

      - name: extract game version
        id: get_version
        run: |
          IMAGE="${{ github.repository }}:local"
          VERSION=$(docker run --rm $IMAGE --version 2>&1 | sed -n 's/.*ver\. \([0-9.]*\).*/\1/p')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  push:
    runs-on: ubuntu-latest
    needs: build
    if: needs.check-image.outputs.exists == 'false'
    steps:
      - name: log in to container registry [github]
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: log in to container registry [docker]
        uses: docker/login-action@v3.6.0
        with:
          registry: docker.io
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: tag image
        run: |
          IMAGE=${{ github.repository }}:local
          BUILD_ID=${{ needs.prepare.outputs.build_id }}
          BRANCH=${{ inputs.branch }}

          if [ "$BRANCH" = "public" ]; then
            docker tag $IMAGE ghcr.io/${{ github.repository }}:latest
            docker tag $IMAGE docker.io/${{ github.repository }}:latest
          fi

          docker tag $IMAGE ghcr.io/${{ github.repository }}:${BRANCH}-${BUILD_ID}
          docker tag $IMAGE docker.io/${{ github.repository }}:${BRANCH}-${BUILD_ID}

      - name: push image
        run: |
          BRANCH=${{ inputs.branch }}
          BUILD_ID=${{ needs.prepare.outputs.build_id }}

          if [ "$BRANCH" = "public" ]; then
            docker push ghcr.io/${{ github.repository }}:latest
            docker push docker.io/${{ github.repository }}:latest
          fi

          docker push ghcr.io/${{ github.repository }}:${BRANCH}-${BUILD_ID}
          docker push docker.io/${{ github.repository }}:${BRANCH}-${BUILD_ID}
